### ISSUE TITLE
Replace terminal prints with structured logging

### ISSUE THREAD

**Issue by Vad1mo** [container-registry/harbor-satellite#24]
We need to start using a logging library/functionality. 

- https://go.dev/blog/slog
- https://betterstack.com/community/guides/logging/best-golang-logging-libraries/

**Comment by mohzulfikar** [comment]
From what I read on the blog, **zerolog** and **slog** appear to be viable options for logging. **zerolog**, seems to come with more features out of the box (formatting logs and contextual properties). Although, it is possible to do that using custom Handler in **slog**.
