### ISSUE TITLE
Comparing Skopeo and Crane for our use case

### ISSUE THREAD

**Issue by WarWolf89** [container-registry/harbor-satellite#3]
We need to better understand if using Skopeo or Kranke would allow us to better replicate images src->dst.

**Uses Cases**
- [ ] Programmable, can be used as an SDK
- [ ] Configuration can be done via API
- [ ] Move OCI Artifacts
- [ ] Remapping Artifacts (programmatically)
- [ ] Image Consistency Verification (was it really pulled correctly, is it present)
- [ ] Memory and CPU consumption on low end devices, Disk consumption
- [ ] Dealing with Low bandwidth networks, resume, etc.

**Comment by OneFlyingBanana** [comment]
Relevant documentation comparing Skopeo and Crane can be found under docs/skopeo-vs-crane.md
