### ISSUE TITLE
Create Dagger CI/CD 

### ISSUE THREAD

**Issue by Vad1mo** [container-registry/harbor-satellite#35]
We should use Dagger for building and testing satellite and groundctontrol 

## With Dagger
- [x] build satellite and ground control binaries
- [x] build images for satellite and ground control 
- [x] Release process for satellite and ground control, each independent of the other.
- [x] Run unit test
- [x] Run integration tests

**Comment by kunal-511** [comment]
For this issue, I need to start containerizing the application first (writing docker files)?

**Comment by milinddethe15** [comment]
Working on this.

**Comment by milinddethe15** [comment]
@Mehul-Kumar-27 Great work! and thanks for wasting my time.
